### ISSUE TITLE
use $::lsbmajdistrelease instead of $::os_maj_version

### ISSUE THREAD

**Issue by felipe1982** [Mylezeem/puppet-repoforge#9]
Mirrors file is written incorrectly. Breaks on puppet 2.7.25 2.7.26. Change to $::lsbmajdistrelease and all works as expected.

**Comment by Spredzy** [comment]
Hey @felipe1982,

Thanks for bringing this to my attention.

This module once tried to rely on `$::lsbmajdistrelease` the issue with this fact is that it relies on the `lsb_release` command to be available[1] or this isn't always true.

On the other hand `$::os_maj_version` comes from parsing the release file[2](ie. `/etc/centos-release`, `/etc/debian_version`) who are part of the base distro hence always present.

Nonetheless, it should work and not be broken, could you paste me two links in a comment:
- One with what you actually have in your platform
- One with what you expect to have

Plus the OS you're running please.

Let's find the root cause.

[1] https://github.com/puppetlabs/facter/blob/2.1.0/lib/facter/lsbdistrelease.rb
[2] https://github.com/puppetlabs/facter/blob/2.1.0/lib/facter/operatingsystemrelease.rb#L27-L38
